#ifndef __ERRORS_H__
#define __ERRORS_H__

#define ERROR_NO_SUCCESS											-1
#define ERROR_NO_NFC_DEVICE_FOUND									-100
#define ERROR_NFC_INITIATOR_INIT									-200
#define ERROR_NFC_INITIATOR_SELECT_PASSIVE_TARGET					-201
#define ERROR_NFC_DEVICE_SET_PROPERTY_BOOL_ACTIVATE_FIELD			-301
#define ERROR_NFC_DEVICE_SET_PROPERTY_BOOL_INFINITE_SELECT			-302
#define ERROR_NFC_DEVICE_SET_PROPERTY_BOOL_CRC						-303
#define ERROR_NFC_DEVICE_SET_PROPERTY_BOOL_CRC_RESTORE_M			-304
#define ERROR_NFC_DEVICE_SET_PROPERTY_BOOL_PARITY					-305
#define ERROR_NFC_DEVICE_SET_PROPERTY_BOOL_PARITY_RESTORE_M			-306
#define ERROR_NFC_DEVICE_SET_PROPERTY_BOOL_FRAMING					-307
#define ERROR_NFC_INITIATOR_TRANSCEIVE_BYTES						-400
#define ERROR_NFC_ONLY_MIFARE_CLASSIC_IS_SUPPORTED					-500
#define ERROR_MEMORY_ALLOCATION										-600

#endif // __ERRORS_H__
